# Generated by Django 4.1 on 2022-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image_alter_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githublink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
