# Generated by Django 4.1 on 2022-08-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_githublink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='githublink',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
